// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//


/// <remarks/>
namespace Argentina.Stub.LoginCMSService
{
    [System.Web.Services.WebServiceBinding(Name="LoginCms", Namespace="https://wsaa.afip.gov.ar/ws/services/LoginCms")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class LoginCMSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public LoginCMSService() {
            this.Url = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", ResponseNamespace="http://wsaa.view.sua.dvadac.desein.afip.gov", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("loginCmsReturn")]
        public string loginCms(string in0) {
            object[] results = this.Invoke("loginCms", new object[] {
                        in0});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginloginCms(string in0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("loginCms", new object[] {
                        in0}, callback, asyncState);
        }
        
        public string EndloginCms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
