// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 1.1.4322.2032
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Mono Web Services Description Language Utility
//


/// <remarks/>
/// <remarks>
///Web Service orientado  al  servicio  de Facturacion electronica
///</remarks>
[System.Web.Services.WebServiceBinding(Name="ServiceSoap", Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    public Service() {
        this.Url = "http://servicios1.afip.gov.ar/wsfe/service.asmx";
    }
    
    /// <remarks>
///Retorna la cantidad maxima de registros detalle que puede tener una invocacion al FEAutorizarRequest
///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FERecuperaQTYRequest", RequestNamespace="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace="http://ar.gov.afip.dif.facturaelectronica/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public FERecuperaQTYResponse FERecuperaQTYRequest(FEAuthRequest argAuth) {
        object[] results = this.Invoke("FERecuperaQTYRequest", new object[] {
                    argAuth});
        return ((FERecuperaQTYResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginFERecuperaQTYRequest(FEAuthRequest argAuth, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FERecuperaQTYRequest", new object[] {
                    argAuth}, callback, asyncState);
    }
    
    public FERecuperaQTYResponse EndFERecuperaQTYRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FERecuperaQTYResponse)(results[0]));
    }
    
    /// <remarks>
///Metodo dummy para verificacion de funcionamiento
///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEDummy", RequestNamespace="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace="http://ar.gov.afip.dif.facturaelectronica/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public DummyResponse FEDummy() {
        object[] results = this.Invoke("FEDummy", new object[0]);
        return ((DummyResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginFEDummy(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FEDummy", new object[0], callback, asyncState);
    }
    
    public DummyResponse EndFEDummy(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DummyResponse)(results[0]));
    }
    
    /// <remarks>
///Retorna el ultimo comprobante autorizado  para el  tipo de comprobante /cuit / punto  de venta ingresado
///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FERecuperaLastCMPRequest", RequestNamespace="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace="http://ar.gov.afip.dif.facturaelectronica/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public FERecuperaLastCMPResponse FERecuperaLastCMPRequest(FEAuthRequest argAuth, FELastCMPtype argTCMP) {
        object[] results = this.Invoke("FERecuperaLastCMPRequest", new object[] {
                    argAuth,
                    argTCMP});
        return ((FERecuperaLastCMPResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginFERecuperaLastCMPRequest(FEAuthRequest argAuth, FELastCMPtype argTCMP, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FERecuperaLastCMPRequest", new object[] {
                    argAuth,
                    argTCMP}, callback, asyncState);
    }
    
    public FERecuperaLastCMPResponse EndFERecuperaLastCMPRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FERecuperaLastCMPResponse)(results[0]));
    }
    
    /// <remarks>
///Retorna el ultimo número de Request.
///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEUltNroRequest", RequestNamespace="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace="http://ar.gov.afip.dif.facturaelectronica/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public FEUltNroResponse FEUltNroRequest(FEAuthRequest argAuth) {
        object[] results = this.Invoke("FEUltNroRequest", new object[] {
                    argAuth});
        return ((FEUltNroResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginFEUltNroRequest(FEAuthRequest argAuth, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FEUltNroRequest", new object[] {
                    argAuth}, callback, asyncState);
    }
    
    public FEUltNroResponse EndFEUltNroRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FEUltNroResponse)(results[0]));
    }
    
    /// <remarks>
///Dado un lote de comprobantes retorna el mismo  autorizado  con el CAE otorgado
///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEAutRequest", RequestNamespace="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace="http://ar.gov.afip.dif.facturaelectronica/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public FEResponse FEAutRequest(FEAuthRequest argAuth, FERequest Fer) {
        object[] results = this.Invoke("FEAutRequest", new object[] {
                    argAuth,
                    Fer});
        return ((FEResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginFEAutRequest(FEAuthRequest argAuth, FERequest Fer, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FEAutRequest", new object[] {
                    argAuth,
                    Fer}, callback, asyncState);
    }
    
    public FEResponse EndFEAutRequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FEResponse)(results[0]));
    }
    
    /// <remarks>
///Consulta el CAE.
///</remarks>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ar.gov.afip.dif.facturaelectronica/FEConsultaCAERequest", RequestNamespace="http://ar.gov.afip.dif.facturaelectronica/", ResponseNamespace="http://ar.gov.afip.dif.facturaelectronica/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    public FEConsultaCAEResponse FEConsultaCAERequest(FEAuthRequest argAuth, FEConsultaCAEReq argCAERequest) {
        object[] results = this.Invoke("FEConsultaCAERequest", new object[] {
                    argAuth,
                    argCAERequest});
        return ((FEConsultaCAEResponse)(results[0]));
    }
    
    public System.IAsyncResult BeginFEConsultaCAERequest(FEAuthRequest argAuth, FEConsultaCAEReq argCAERequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FEConsultaCAERequest", new object[] {
                    argAuth,
                    argCAERequest}, callback, asyncState);
    }
    
    public FEConsultaCAEResponse EndFEConsultaCAERequest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((FEConsultaCAEResponse)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEAuthRequest {
    
    /// <remarks/>
    public string Token;
    
    /// <remarks/>
    public string Sign;
    
    /// <remarks/>
    public long cuit;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FERecuperaQTYResponse {
    
    /// <remarks/>
    public FERecuperaQTY qty;
    
    /// <remarks/>
    public vError RError;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FERecuperaQTY {
    
    /// <remarks/>
    public int value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class vError {
    
    /// <remarks/>
    public int percode;
    
    /// <remarks/>
    public string perrmsg;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class DummyResponse {
    
    /// <remarks/>
    public string appserver;
    
    /// <remarks/>
    public string dbserver;
    
    /// <remarks/>
    public string authserver;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FELastCMPtype {
    
    /// <remarks/>
    public int PtoVta;
    
    /// <remarks/>
    public int TipoCbte;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FERecuperaLastCMPResponse {
    
    /// <remarks/>
    public int cbte_nro;
    
    /// <remarks/>
    public vError RError;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEUltNroResponse {
    
    /// <remarks/>
    public UltNroResponse nro;
    
    /// <remarks/>
    public vError RError;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class UltNroResponse {
    
    /// <remarks/>
    public long value;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FERequest {
    
    /// <remarks/>
    public FECabeceraRequest Fecr;
    
    /// <remarks/>
    public FEDetalleRequest[] Fedr;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FECabeceraRequest {
    
    /// <remarks/>
    public long id;
    
    /// <remarks/>
    public int cantidadreg;
    
    /// <remarks/>
    public int presta_serv;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEDetalleRequest {
    
    /// <remarks/>
    public int tipo_doc;
    
    /// <remarks/>
    public long nro_doc;
    
    /// <remarks/>
    public int tipo_cbte;
    
    /// <remarks/>
    public int punto_vta;
    
    /// <remarks/>
    public long cbt_desde;
    
    /// <remarks/>
    public long cbt_hasta;
    
    /// <remarks/>
    public System.Double imp_total;
    
    /// <remarks/>
    public System.Double imp_tot_conc;
    
    /// <remarks/>
    public System.Double imp_neto;
    
    /// <remarks/>
    public System.Double impto_liq;
    
    /// <remarks/>
    public System.Double impto_liq_rni;
    
    /// <remarks/>
    public System.Double imp_op_ex;
    
    /// <remarks/>
    public string fecha_cbte;
    
    /// <remarks/>
    public string fecha_serv_desde;
    
    /// <remarks/>
    public string fecha_serv_hasta;
    
    /// <remarks/>
    public string fecha_venc_pago;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEResponse {
    
    /// <remarks/>
    public FECabeceraResponse FecResp;
    
    /// <remarks/>
    public FEDetalleResponse[] FedResp;
    
    /// <remarks/>
    public vError RError;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FECabeceraResponse {
    
    /// <remarks/>
    public long id;
    
    /// <remarks/>
    public long cuit;
    
    /// <remarks/>
    public string fecha_cae;
    
    /// <remarks/>
    public int cantidadreg;
    
    /// <remarks/>
    public string resultado;
    
    /// <remarks/>
    public string motivo;
    
    /// <remarks/>
    public string reproceso;
    
    /// <remarks/>
    public int presta_serv;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEDetalleResponse {
    
    /// <remarks/>
    public int tipo_doc;
    
    /// <remarks/>
    public long nro_doc;
    
    /// <remarks/>
    public int tipo_cbte;
    
    /// <remarks/>
    public int punto_vta;
    
    /// <remarks/>
    public long cbt_desde;
    
    /// <remarks/>
    public long cbt_hasta;
    
    /// <remarks/>
    public System.Double imp_total;
    
    /// <remarks/>
    public System.Double imp_tot_conc;
    
    /// <remarks/>
    public System.Double imp_neto;
    
    /// <remarks/>
    public System.Double impto_liq;
    
    /// <remarks/>
    public System.Double impto_liq_rni;
    
    /// <remarks/>
    public System.Double imp_op_ex;
    
    /// <remarks/>
    public string resultado;
    
    /// <remarks/>
    public string cae;
    
    /// <remarks/>
    public string fecha_cbte;
    
    /// <remarks/>
    public string fecha_vto;
    
    /// <remarks/>
    public string motivo;
    
    /// <remarks/>
    public string fecha_serv_desde;
    
    /// <remarks/>
    public string fecha_serv_hasta;
    
    /// <remarks/>
    public string fecha_venc_pago;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEConsultaCAEReq {
    
    /// <remarks/>
    public long cuit_emisor;
    
    /// <remarks/>
    public int tipo_cbte;
    
    /// <remarks/>
    public int punto_vta;
    
    /// <remarks/>
    public long cbt_nro;
    
    /// <remarks/>
    public System.Double imp_total;
    
    /// <remarks/>
    public string cae;
    
    /// <remarks/>
    public string fecha_cbte;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ar.gov.afip.dif.facturaelectronica/")]
public class FEConsultaCAEResponse {
    
    /// <remarks/>
    public int Resultado;
    
    /// <remarks/>
    public vError RError;
}
